services:

  caddy:
    image: caddy:2

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config

    depends_on:
      - website
      - send
      - rate-limit-demo
      - blackjack

  website:
    image: ghcr.io/mastermetarn/norum-web:latest

    restart: unless-stopped

  send:
    image: ghcr.io/mastermetarn/send:latest

    restart: unless-stopped

  rate-limit-demo:
    image: ghcr.io/mastermetarn/rate-limit-demo:latest

    restart: unless-stopped

  blackjack:
    image: ghcr.io/mastermetarn/adrino-alesive-project:latest

    restart: unless-stopped

    environment:
      PORT: "8989"
      DATA_DIR: /app/data
      RESET_DATA_ON_START: "true"
      TZ: Europe/Stockholm

    volumes:
      - blackjack-data:/app/data

volumes:
  blackjack-data:
